# Generated by Django 3.1 on 2022-01-27 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterModelOptions(
            name='cartitems',
            options={'verbose_name': 'CartItems', 'verbose_name_plural': 'CartItems'},
        ),
    ]
