# Generated by Django 3.1 on 2022-01-27 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20220128_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitems',
            options={'verbose_name': 'CartItem', 'verbose_name_plural': 'CartItems'},
        ),
    ]
