# Generated by Django 3.1 on 2022-01-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20220128_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='added_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='added_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
