# Generated by Django 3.1 on 2022-02-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20220203_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
