# Generated by Django 3.1 on 2022-02-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cartitems_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_total',
            field=models.IntegerField(default=0),
        ),
    ]
